### PR TITLE
Don't force TLS version. Let curl decide.

### PR DESCRIPTION
**Pull request by nilleroux**

### CODE REVIEW

**Comment by camilletyan** [comment]
@gaillafr please let me know how soon you can merge this pull request as we will soon stop supporting TLS 1.0

**Comment by Quetzacoalt91** [comment]
Hi @camilletyan,

What are you going to support instead ? We use this option in order to use TLS instead of SSL (Because of the Poodle security issue).

Best regards

**Comment by camilletyan** [comment]
We are fully aware of the Poodle issue, and we will soon only support TLS 1.2. The proposed commit will enable cURL to inquire from our server the appropriate HTTPS protocol to be used.

**Comment by camilletyan** [comment]
@Quetzacoalt91 @gaillafr We are about to stop supporting TLS 1.0 tomorrow. Can you please let me know when you will be able to merge this pull request and update the module in Prestashop and the add-ons site?

**Comment by camilletyan** [comment]
Merci Francois. Does that mean that the plugin is also updated on
Prestashop download and addons?

**Comment by gaillafr** [comment]
You're welcome.
Sorry but we have to wait til tomorrow for the module to be synced on the marketplaced.
The new version should be available tomorrow.

Thank you for this fix,
Kind regards.

**Pull request merged**
